package com.silence.robot.mapper;

import java.util.List;

import com.silence.robot.model.TBusinessInfo;
import com.silence.robot.model.TCronTask;

public interface TBusinessInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int insert(TBusinessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    TBusinessInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    List<TBusinessInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBusinessInfo record);

    void updateByBusinessName(TBusinessInfo businessInfo);

    void deleteByBusinessName(String businessName);

    List<TBusinessInfo> selectByBusinessDesc(String businessDesc);
}