package com.silence.robot.mapper;

import java.util.List;

import com.silence.robot.model.TCommemoratingInfo;

public interface TCommemoratingInfoMapper {

    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int insert(TCommemoratingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    TCommemoratingInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    List<TCommemoratingInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCommemoratingInfo record);
}
