package com.silence.robot.mapper;

import com.silence.robot.model.TCronTaskProcLog;
import java.util.List;

public interface TCronTaskProcLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task_proc_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task_proc_log
     *
     * @mbg.generated
     */
    int insert(TCronTaskProcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task_proc_log
     *
     * @mbg.generated
     */
    TCronTaskProcLog selectByPrimaryKey(String id);
    TCronTaskProcLog selectByJobName(String jobName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task_proc_log
     *
     * @mbg.generated
     */
    List<TCronTaskProcLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task_proc_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCronTaskProcLog record);
}