package com.silence.robot.mapper;

import com.silence.robot.model.TCronTask;
import java.util.List;

public interface TCronTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int insert(TCronTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    TCronTask selectByPrimaryKey(String id);
    TCronTask selectByJobName(String jobName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    List<TCronTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCronTask record);
}