package com.silence.robot.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.silence.robot.model.TMemberInfo;
import com.silence.robot.model.TMemberTransDetail;

public interface TMemberTransDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int insert(TMemberTransDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    TMemberTransDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    List<TMemberTransDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMemberTransDetail record);

    List<TMemberTransDetail> selectByCondition(@Param("collect") List<String> collect);
}