package com.silence.robot.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.silence.robot.model.TMemberInfo;
import com.silence.robot.model.TMerchantInfo;

public interface TMemberInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int insert(TMemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    TMemberInfo selectByPrimaryKey(String id);
    TMemberInfo selectByMemberName(String memberName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    List<TMemberInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMemberInfo record);

    void updateByMemberName(TMemberInfo memberInfo);
    void updateBalance(TMemberInfo memberInfo);

    void deleteByMemberName(String memberName);

    List<TMemberInfo> selectByCondition(@Param("memberDesc") String memberDesc, @Param("memberPhone") String memberPhone);
}