package com.silence.robot.mapper;

import com.silence.robot.model.TMenu;

import java.util.List;

public interface TMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);
    int deleteByMenuNo(String menuNo);
    int deleteByParentMenuNo(String parentMenuNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated
     */
    int insert(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated
     */
    TMenu selectByPrimaryKey(String id);
    TMenu selectByMenuNo(String menuNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated
     */
    List<TMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMenu record);
}