package com.silence.robot.mapper;

import java.util.List;

import com.silence.robot.model.TBusinessInfo;
import com.silence.robot.model.TMerchantInfo;

public interface TMerchantInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int insert(TMerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    TMerchantInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    List<TMerchantInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cron_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMerchantInfo record);

    void deleteByMerchantName(String merchantName);

    List<TMerchantInfo> selectByCondition(String merchantDesc);

    void updateByMerchantName(TMerchantInfo merchantInfo);
}