package com.silence.robot.mapper;

import com.silence.robot.model.TSequence;
import java.util.List;

public interface TSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbg.generated
     */
    int insert(TSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbg.generated
     */
    TSequence selectByPrimaryKey(String id);
    TSequence selectBySeqName(String seqName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbg.generated
     */
    List<TSequence> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSequence record);
}