package com.silence.robot.mapper;

import com.silence.robot.model.TSubscribeConfigInfo;
import java.util.List;

public interface TSubscribeConfigInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_config_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_config_info
     *
     * @mbg.generated
     */
    int insert(TSubscribeConfigInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_config_info
     *
     * @mbg.generated
     */
    TSubscribeConfigInfo selectByPrimaryKey(String id);
    TSubscribeConfigInfo selectByConfigName(String configName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_config_info
     *
     * @mbg.generated
     */
    List<TSubscribeConfigInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_config_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSubscribeConfigInfo record);
}