package com.silence.robot.mapper;

import com.silence.robot.model.TSubscribeConfigInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TSubscribeConfigInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_config_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);
    int deleteAndBatchById(List<String> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_config_info
     *
     * @mbg.generated
     */
    int insert(TSubscribeConfigInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_config_info
     *
     * @mbg.generated
     */
    TSubscribeConfigInfo selectByPrimaryKey(String id);
    TSubscribeConfigInfo selectByConfigName(String configName);
    TSubscribeConfigInfo selectByConfigNameAndUsername(@Param("configName") String configName, @Param("createUser") String createUser);
    List<TSubscribeConfigInfo> selectByCreateUser(String createUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_config_info
     *
     * @mbg.generated
     */
    List<TSubscribeConfigInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_config_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSubscribeConfigInfo record);
}