package com.silence.robot.mapper;

import com.silence.robot.model.TSvnInfo;
import java.util.List;

public interface TSvnInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_svn_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_svn_info
     *
     * @mbg.generated
     */
    int insert(TSvnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_svn_info
     *
     * @mbg.generated
     */
    TSvnInfo selectByPrimaryKey(String id);
    TSvnInfo selectByUrl(String url);
    List<TSvnInfo> selectByOverFlag(String overFlag);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_svn_info
     *
     * @mbg.generated
     */
    List<TSvnInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_svn_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSvnInfo record);
}