package com.silence.robot.mapper;

import com.silence.robot.model.TUserTalkFriend;
import java.util.List;

public interface TUserTalkFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_friend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    int deleteByMineId(String mineId);

    int deleteByFriendId(String friendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_friend
     *
     * @mbg.generated
     */
    int insert(TUserTalkFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_friend
     *
     * @mbg.generated
     */
    TUserTalkFriend selectByPrimaryKey(String id);
    List<TUserTalkFriend> selectByMineId(String mindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_friend
     *
     * @mbg.generated
     */
    List<TUserTalkFriend> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TUserTalkFriend record);
}