package com.silence.robot.mapper;

import com.silence.robot.model.TUserTalkFriendGroup;
import java.util.List;

public interface TUserTalkFriendGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_friend_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_friend_group
     *
     * @mbg.generated
     */
    int insert(TUserTalkFriendGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_friend_group
     *
     * @mbg.generated
     */
    TUserTalkFriendGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_friend_group
     *
     * @mbg.generated
     */
    List<TUserTalkFriendGroup> selectAll();
    List<TUserTalkFriendGroup> selectByMineId(String mineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_friend_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TUserTalkFriendGroup record);
}