package com.silence.robot.mapper;

import com.silence.robot.model.TUserTalkInfo;
import java.util.List;

public interface TUserTalkInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_info
     *
     * @mbg.generated
     */
    int insert(TUserTalkInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_info
     *
     * @mbg.generated
     */
    TUserTalkInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_info
     *
     * @mbg.generated
     */
    List<TUserTalkInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TUserTalkInfo record);
}