package com.silence.robot.mapper;

import com.silence.robot.model.TUserTalkGroup;
import java.util.List;

public interface TUserTalkGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_group
     *
     * @mbg.generated
     */
    int insert(TUserTalkGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_group
     *
     * @mbg.generated
     */
    TUserTalkGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_group
     *
     * @mbg.generated
     */
    List<TUserTalkGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_talk_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TUserTalkGroup record);
}