package com.silence.robot.model;

import java.util.Date;

public class TCronTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cron_task.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cron_task.job_name
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cron_task.cron_expr
     *
     * @mbg.generated
     */
    private String cronExpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cron_task.job_desc
     *
     * @mbg.generated
     */
    private String jobDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cron_task.job_class
     *
     * @mbg.generated
     */
    private String jobClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cron_task.effect_flag
     *
     * @mbg.generated
     */
    private String effectFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cron_task.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cron_task.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cron_task.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cron_task.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cron_task.ID
     *
     * @return the value of t_cron_task.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cron_task.ID
     *
     * @param id the value for t_cron_task.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cron_task.job_name
     *
     * @return the value of t_cron_task.job_name
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cron_task.job_name
     *
     * @param jobName the value for t_cron_task.job_name
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cron_task.cron_expr
     *
     * @return the value of t_cron_task.cron_expr
     *
     * @mbg.generated
     */
    public String getCronExpr() {
        return cronExpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cron_task.cron_expr
     *
     * @param cronExpr the value for t_cron_task.cron_expr
     *
     * @mbg.generated
     */
    public void setCronExpr(String cronExpr) {
        this.cronExpr = cronExpr == null ? null : cronExpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cron_task.job_desc
     *
     * @return the value of t_cron_task.job_desc
     *
     * @mbg.generated
     */
    public String getJobDesc() {
        return jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cron_task.job_desc
     *
     * @param jobDesc the value for t_cron_task.job_desc
     *
     * @mbg.generated
     */
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc == null ? null : jobDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cron_task.job_class
     *
     * @return the value of t_cron_task.job_class
     *
     * @mbg.generated
     */
    public String getJobClass() {
        return jobClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cron_task.job_class
     *
     * @param jobClass the value for t_cron_task.job_class
     *
     * @mbg.generated
     */
    public void setJobClass(String jobClass) {
        this.jobClass = jobClass == null ? null : jobClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cron_task.effect_flag
     *
     * @return the value of t_cron_task.effect_flag
     *
     * @mbg.generated
     */
    public String getEffectFlag() {
        return effectFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cron_task.effect_flag
     *
     * @param effectFlag the value for t_cron_task.effect_flag
     *
     * @mbg.generated
     */
    public void setEffectFlag(String effectFlag) {
        this.effectFlag = effectFlag == null ? null : effectFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cron_task.create_user
     *
     * @return the value of t_cron_task.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cron_task.create_user
     *
     * @param createUser the value for t_cron_task.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cron_task.create_time
     *
     * @return the value of t_cron_task.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cron_task.create_time
     *
     * @param createTime the value for t_cron_task.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cron_task.update_user
     *
     * @return the value of t_cron_task.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cron_task.update_user
     *
     * @param updateUser the value for t_cron_task.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cron_task.update_time
     *
     * @return the value of t_cron_task.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cron_task.update_time
     *
     * @param updateTime the value for t_cron_task.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}