package com.silence.robot.model;

import java.util.Date;

public class TMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.MENU_NO
     *
     * @mbg.generated
     */
    private String menuNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.MENU_NAME
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.MENU_PATH
     *
     * @mbg.generated
     */
    private String menuPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.PARENT_MENU_NO
     *
     * @mbg.generated
     */
    private String parentMenuNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.MENU_LEVEL
     *
     * @mbg.generated
     */
    private Integer menuLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.MENU_SEQ_NO
     *
     * @mbg.generated
     */
    private Integer menuSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.UPDATE_USER
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.ID
     *
     * @return the value of t_menu.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.ID
     *
     * @param id the value for t_menu.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.MENU_NO
     *
     * @return the value of t_menu.MENU_NO
     *
     * @mbg.generated
     */
    public String getMenuNo() {
        return menuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.MENU_NO
     *
     * @param menuNo the value for t_menu.MENU_NO
     *
     * @mbg.generated
     */
    public void setMenuNo(String menuNo) {
        this.menuNo = menuNo == null ? null : menuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.MENU_NAME
     *
     * @return the value of t_menu.MENU_NAME
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.MENU_NAME
     *
     * @param menuName the value for t_menu.MENU_NAME
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.MENU_PATH
     *
     * @return the value of t_menu.MENU_PATH
     *
     * @mbg.generated
     */
    public String getMenuPath() {
        return menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.MENU_PATH
     *
     * @param menuPath the value for t_menu.MENU_PATH
     *
     * @mbg.generated
     */
    public void setMenuPath(String menuPath) {
        this.menuPath = menuPath == null ? null : menuPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.PARENT_MENU_NO
     *
     * @return the value of t_menu.PARENT_MENU_NO
     *
     * @mbg.generated
     */
    public String getParentMenuNo() {
        return parentMenuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.PARENT_MENU_NO
     *
     * @param parentMenuNo the value for t_menu.PARENT_MENU_NO
     *
     * @mbg.generated
     */
    public void setParentMenuNo(String parentMenuNo) {
        this.parentMenuNo = parentMenuNo == null ? null : parentMenuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.MENU_LEVEL
     *
     * @return the value of t_menu.MENU_LEVEL
     *
     * @mbg.generated
     */
    public Integer getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.MENU_LEVEL
     *
     * @param menuLevel the value for t_menu.MENU_LEVEL
     *
     * @mbg.generated
     */
    public void setMenuLevel(Integer menuLevel) {
        this.menuLevel = menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.MENU_SEQ_NO
     *
     * @return the value of t_menu.MENU_SEQ_NO
     *
     * @mbg.generated
     */
    public Integer getMenuSeqNo() {
        return menuSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.MENU_SEQ_NO
     *
     * @param menuSeqNo the value for t_menu.MENU_SEQ_NO
     *
     * @mbg.generated
     */
    public void setMenuSeqNo(Integer menuSeqNo) {
        this.menuSeqNo = menuSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.CREATE_TIME
     *
     * @return the value of t_menu.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.CREATE_TIME
     *
     * @param createTime the value for t_menu.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.CREATE_USER
     *
     * @return the value of t_menu.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.CREATE_USER
     *
     * @param createUser the value for t_menu.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.UPDATE_TIME
     *
     * @return the value of t_menu.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.UPDATE_TIME
     *
     * @param updateTime the value for t_menu.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.UPDATE_USER
     *
     * @return the value of t_menu.UPDATE_USER
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.UPDATE_USER
     *
     * @param updateUser the value for t_menu.UPDATE_USER
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}