package com.silence.robot.model;

public class TSequence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sequence.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sequence.seq_name
     *
     * @mbg.generated
     */
    private String seqName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sequence.seq_value
     *
     * @mbg.generated
     */
    private Integer seqValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sequence.id
     *
     * @return the value of t_sequence.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequence.id
     *
     * @param id the value for t_sequence.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sequence.seq_name
     *
     * @return the value of t_sequence.seq_name
     *
     * @mbg.generated
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequence.seq_name
     *
     * @param seqName the value for t_sequence.seq_name
     *
     * @mbg.generated
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName == null ? null : seqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sequence.seq_value
     *
     * @return the value of t_sequence.seq_value
     *
     * @mbg.generated
     */
    public Integer getSeqValue() {
        return seqValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequence.seq_value
     *
     * @param seqValue the value for t_sequence.seq_value
     *
     * @mbg.generated
     */
    public void setSeqValue(Integer seqValue) {
        this.seqValue = seqValue;
    }
}