package com.silence.robot.model;

import java.util.Date;

public class TSubscribeConfigInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_config_info.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_config_info.config_name
     *
     * @mbg.generated
     */
    private String configName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_config_info.config_value
     *
     * @mbg.generated
     */
    private String configValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_config_info.config_desc
     *
     * @mbg.generated
     */
    private String configDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_config_info.expire_time
     *
     * @mbg.generated
     */
    private Integer expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_config_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_config_info.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_config_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_config_info.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_config_info.ID
     *
     * @return the value of t_subscribe_config_info.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_config_info.ID
     *
     * @param id the value for t_subscribe_config_info.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_config_info.config_name
     *
     * @return the value of t_subscribe_config_info.config_name
     *
     * @mbg.generated
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_config_info.config_name
     *
     * @param configName the value for t_subscribe_config_info.config_name
     *
     * @mbg.generated
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_config_info.config_value
     *
     * @return the value of t_subscribe_config_info.config_value
     *
     * @mbg.generated
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_config_info.config_value
     *
     * @param configValue the value for t_subscribe_config_info.config_value
     *
     * @mbg.generated
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_config_info.config_desc
     *
     * @return the value of t_subscribe_config_info.config_desc
     *
     * @mbg.generated
     */
    public String getConfigDesc() {
        return configDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_config_info.config_desc
     *
     * @param configDesc the value for t_subscribe_config_info.config_desc
     *
     * @mbg.generated
     */
    public void setConfigDesc(String configDesc) {
        this.configDesc = configDesc == null ? null : configDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_config_info.expire_time
     *
     * @return the value of t_subscribe_config_info.expire_time
     *
     * @mbg.generated
     */
    public Integer getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_config_info.expire_time
     *
     * @param expireTime the value for t_subscribe_config_info.expire_time
     *
     * @mbg.generated
     */
    public void setExpireTime(Integer expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_config_info.create_time
     *
     * @return the value of t_subscribe_config_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_config_info.create_time
     *
     * @param createTime the value for t_subscribe_config_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_config_info.create_user
     *
     * @return the value of t_subscribe_config_info.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_config_info.create_user
     *
     * @param createUser the value for t_subscribe_config_info.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_config_info.update_time
     *
     * @return the value of t_subscribe_config_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_config_info.update_time
     *
     * @param updateTime the value for t_subscribe_config_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_config_info.update_user
     *
     * @return the value of t_subscribe_config_info.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_config_info.update_user
     *
     * @param updateUser the value for t_subscribe_config_info.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}