package com.silence.robot.model;

public class TSvnInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_svn_info.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_svn_info.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_svn_info.local_url
     *
     * @mbg.generated
     */
    private String localUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_svn_info.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_svn_info.over_flag
     *
     * @mbg.generated
     */
    private String overFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_svn_info.ID
     *
     * @return the value of t_svn_info.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_svn_info.ID
     *
     * @param id the value for t_svn_info.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_svn_info.url
     *
     * @return the value of t_svn_info.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_svn_info.url
     *
     * @param url the value for t_svn_info.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_svn_info.local_url
     *
     * @return the value of t_svn_info.local_url
     *
     * @mbg.generated
     */
    public String getLocalUrl() {
        return localUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_svn_info.local_url
     *
     * @param localUrl the value for t_svn_info.local_url
     *
     * @mbg.generated
     */
    public void setLocalUrl(String localUrl) {
        this.localUrl = localUrl == null ? null : localUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_svn_info.remark
     *
     * @return the value of t_svn_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_svn_info.remark
     *
     * @param remark the value for t_svn_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_svn_info.over_flag
     *
     * @return the value of t_svn_info.over_flag
     *
     * @mbg.generated
     */
    public String getOverFlag() {
        return overFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_svn_info.over_flag
     *
     * @param overFlag the value for t_svn_info.over_flag
     *
     * @mbg.generated
     */
    public void setOverFlag(String overFlag) {
        this.overFlag = overFlag == null ? null : overFlag.trim();
    }
}