package com.silence.robot.model;

public class TUserTalkMembers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_talk_members.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_talk_members.group_id
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_talk_members.member_id
     *
     * @mbg.generated
     */
    private String memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_talk_members.id
     *
     * @return the value of t_user_talk_members.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_talk_members.id
     *
     * @param id the value for t_user_talk_members.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_talk_members.group_id
     *
     * @return the value of t_user_talk_members.group_id
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_talk_members.group_id
     *
     * @param groupId the value for t_user_talk_members.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_talk_members.member_id
     *
     * @return the value of t_user_talk_members.member_id
     *
     * @mbg.generated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_talk_members.member_id
     *
     * @param memberId the value for t_user_talk_members.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }
}