package com.silence.robot.model;

public class TUserTalkFriend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_talk_friend.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_talk_friend.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_talk_friend.mine_id
     *
     * @mbg.generated
     */
    private String mineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_talk_friend.friend_id
     *
     * @mbg.generated
     */
    private String friendId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_talk_friend.id
     *
     * @return the value of t_user_talk_friend.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_talk_friend.id
     *
     * @param id the value for t_user_talk_friend.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_talk_friend.group_id
     *
     * @return the value of t_user_talk_friend.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_talk_friend.group_id
     *
     * @param groupId the value for t_user_talk_friend.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_talk_friend.mine_id
     *
     * @return the value of t_user_talk_friend.mine_id
     *
     * @mbg.generated
     */
    public String getMineId() {
        return mineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_talk_friend.mine_id
     *
     * @param mineId the value for t_user_talk_friend.mine_id
     *
     * @mbg.generated
     */
    public void setMineId(String mineId) {
        this.mineId = mineId == null ? null : mineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_talk_friend.friend_id
     *
     * @return the value of t_user_talk_friend.friend_id
     *
     * @mbg.generated
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_talk_friend.friend_id
     *
     * @param friendId the value for t_user_talk_friend.friend_id
     *
     * @mbg.generated
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId == null ? null : friendId.trim();
    }
}