package com.silence.robot.model;

public class TUserTalkGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_talk_group.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_talk_group.groupname
     *
     * @mbg.generated
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_talk_group.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_talk_group.id
     *
     * @return the value of t_user_talk_group.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_talk_group.id
     *
     * @param id the value for t_user_talk_group.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_talk_group.groupname
     *
     * @return the value of t_user_talk_group.groupname
     *
     * @mbg.generated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_talk_group.groupname
     *
     * @param groupname the value for t_user_talk_group.groupname
     *
     * @mbg.generated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_talk_group.avatar
     *
     * @return the value of t_user_talk_group.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_talk_group.avatar
     *
     * @param avatar the value for t_user_talk_group.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }
}