spring:
  datasource:
    write:
      url: jdbc:mysql://local.silence.com:3307/robot
      username: ENC(wDr6mWeyMF4Xyl8nojBZmw==)
      password: ENC(NnkDNOxHTaEju3+FeK2YRw==)
    read:
      url: jdbc:mysql://local.silence.com:3308/robot
      username: ENC(wDr6mWeyMF4Xyl8nojBZmw==)
      password: ENC(NnkDNOxHTaEju3+FeK2YRw==)
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000