silence:
  filter:
    cors: true
  interceptor:
    paths:
      - /login
      - /getUser
      - /verifyCode
robot:
  api:
    url: http://openapi.tuling123.com/openapi/api/v2
    userId: 508353
    key: db102bba955342ee8e32c2e3f317704e
server:
  port: 8081
spring:
  profiles:
    active: mysql
logging:
  level:
    root: info
    com.silence.robot.mapper: debug
  path: logs
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
