spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    write:
      url: jdbc:h2:mem:robotdb;DB_CLOSE_DELAY=-1;MODE=MySQL;AUTO_RECONNECT=TRUE
      username: sa
      password: sa
      schema: classpath:db/schema.sql
      data: classpath:db/data.sql
    read:
      url: jdbc:h2:mem:robotdb;DB_CLOSE_DELAY=-1;MODE=MySQL;AUTO_RECONNECT=TRUE
      username: sa
      password: sa
      schema: classpath:db/schema.sql
      data: classpath:db/data.sql