silence:
  filter:
    cors: true
  subscribe:
    token: ENC(z/adb94Kn/PADnCarciDoFyDO1kQAcBn)
  aliyun:
    ocr:
      uri: http://form.market.alicloudapi.com/api/predict/ocr_table_parse
      appCode: 8cf623998ddf4f07b9ea67749eeb8ce8
  interceptor:
    paths:
      - /login
      - /getUser
      - /verifyCode
      - /mock
      - /signature/*
      - /swagger-ui.html/**
      - /swagger-ui.html
      - /webjars/**
      - /swagger-resources/**
      - /v2/**
  wechat:
    subscribe:
      api: https://api.weixin.qq.com/cgi-bin/token
      grant_type: client_credential
      appid: wxbaa91f7312261743
      secret: 35245d830d87fd703eb79df651cdceb5
  swagger:
    enable: true
robot:
  api:
    url: http://openapi.tuling123.com/openapi/api/v2
    userId: 508353
    key: db102bba955342ee8e32c2e3f317704e
server:
  port: 18002
spring:
  profiles:
    active: sqlite
logging:
  level:
    root: info
    com.silence.robot.mapper: debug
  path: logs
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
