silence:
  filter:
    cors: true
  subscribe:
    token: ENC(z/adb94Kn/PADnCarciDoFyDO1kQAcBn)
  interceptor:
    paths:
      - /
      - /error
      - /login
      - /getUser
      - /verifyCode
      - /signature/*
  wechat:
    subscribe:
      api: https://api.weixin.qq.com/cgi-bin/token
      grant_type: client_credential
      appid: wxbaa91f7312261743
      secret: 35245d830d87fd703eb79df651cdceb5
robot:
  api:
    url: http://openapi.tuling123.com/openapi/api/v2
    userId: 508353
    key: db102bba955342ee8e32c2e3f317704e
server:
  port: 8081
spring:
  profiles:
    active: mysql
logging:
  level:
    root: info
    com.silence.robot.mapper: debug
  path: logs
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
