spring:
  datasource:
    write:
      url: jdbc:sqlite:${sqlite.url}?date_string_format=yyyy-MM-dd HH:mm:ss
    read:
      url: jdbc:sqlite:${sqlite.url}?date_string_format=yyyy-MM-dd HH:mm:ss
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  redis:
    host: 192.168.56.10
sqlite:
  url: D:\test\robot.db
silence:
  loan:
    dayCutPath: D:\test\dayCut\