spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:robotdb;DB_CLOSE_DELAY=-1;MODE=MySQL;AUTO_RECONNECT=TRUE
    username: sa
    password: sa
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql