silence:
  filter:
    cors: true
robot:
  api:
    url: http://openapi.tuling123.com/openapi/api/v2
    userId: 508353
    key: db102bba955342ee8e32c2e3f317704e
server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:robotdb;DB_CLOSE_DELAY=-1;MODE=MySQL;AUTO_RECONNECT=TRUE
    username: sa
    password: sa
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
logging:
  level:
    root: DEBUG